### PR TITLE
Skin support final implementation

### PR DESCRIPTION
**Pull request by Demizdor**
scr

Hey @raysan5 as stated in https://github.com/raysan5/raygui/pull/98 here is another pull request adding support for skinning. Compared to my previous attempt this time i made sure to fix most of the bugs and also included a fully functional skin editor in `/examples/` to make creating/editing skins a bit easier.
 
Here are some features:
- supports almost all the raygui controls except `GuiLine()`, `GuiGroupBox()`, `GuiLabel()`, `GuiGrid()`, `GuiLabelButton()` and `GuiDummyRec()`
- some controls have multiple sub components (ex `GuiListViewEx()` ) those can be skinned too
- a skin file can hold multiple skin styles, this way one can have different skins for the menu GUI, ingame GUI etc. in the same file
- support for saving loading skins to/from a text file, the syntax resembles `.rgs` as much as possible
- if `useColor` is enabled for a skin it can use the currently active color style

Using it in your code is quite easy i think here's an example:
```c
// Loading from a file
GuiSkin skins[4] = {0}; // create an empty array to hold our skins
int skinCount = GuiLoadSkin("test.skin", skins, 4); //load at most 4 skins from file
if(skinCount == 0) TraceLog(LOG_ERROR, "Failed to load skins!"); // handle failure

GuiSetSkin(&skin[0]); // set the first skin as the global skin 
GuiButton(bounds, "Hello"); // render a button using the first skin
GuiSetSkin(&skin[1]);
GuiButton(bounds, "World"); // render a button using the second skin
// ....

// `GuiLoadSkin()` will automatically load a texture file but you can also use your own
GuiSetSkinTexture(mytexture); // now mytexture is the global gui texture.

// Saving a skin to file
GuiSaveSkin("test.skin", "texture.png", skins,  4); // Save 4 skins styles to file
```

Please try the editor to see more of what the current implementation can do!
I think this feature will benefit raygui greatly, so what do you say Ray :+1: or :-1: 

PS: i don't know why **d321a0b** and **37f20a4** are in there :(

### CODE REVIEW

**Comment by raysan5** [comment]
@Demizdor Wow! Really impressive! Congrats! This is a huge change for the library, I need some time to review it and decide...

In any case, thanks for this great feature and tool!

**Comment by Demizdor** [comment]
Sure thing take your time, the update is huge and you'll need to maintain in the future so i fully understand.

**Comment by Demizdor** [comment]
Hey @raysan5 , i will close this!

The new raylib changes broke this code.
Some things are easy to fix like getting rid of the `#ifdef __unix__` hacks adding the dot when calling `GetExtension()` in editor.c and correcting `DrawTextureNPatch()`  to use `NPATCH_NINE_PATCH` in raygui.h but others are harder like the newly patched `GuiScrollPanel()` that made drawing the edges not behave correctly.

I'm sure if i had time everything would work once again but i don't have time to fix things, so i believe this is the best way to handle all of this, sorry!

**Comment by raysan5** [comment]
Hi @Demizdor, ok, no sorry, it's ok. It was a big change and I haven't put much time into raygui lately. I also admit I felt a bit scary about maintaining it... No worries, the PR is here for future reference.

**Pull request closed without merging**
