### PR TITLE
Fix for sliders

### PR DESCRIPTION
**Pull request by hanaxar**
A fix for sliders not dragging outside of bounds.
Added 2 global variables: a state for slider dragging and a rectangle as an identifier for the slider. This way it's possible to fix sliders without breaking changes.

### CODE REVIEW

**Comment by raysan5** [comment]
@hanaxar Wow! What a solution! Does it really work??? Very impressive! Thanks! I need to test it carefully before merging...

**Comment by hanaxar** [comment]
Yes it seems to work. I tested it with ```scroll_panel.c``` and ```controls_test_suite.c``` examples.

**Comment by raysan5** [comment]
@hanaxar Just tested it and it works perfectly! Thank you very much! This is really a great improvement! 😄

**Comment by odecaux** [comment]
We could probably remove most of examples/custom_sliders and only keep GuiVerticalSlider/Bar/Pro()

**Comment by raysan5** [comment]
@odecaux I prefer to keep them for now, they show another way to implement it not relying on a global variable. It could be useful for some users.

**Pull request merged**
