### PR TITLE
Add Toggle Slider (#305)

### PR DESCRIPTION
**Pull request by furudbat**
image

### CODE REVIEW

**Comment by furudbat** [comment]
@raysan5 Not sure how to deal with the style for this control.
I'm currently using the `SLIDER` style for the text.

The problem is the `focus` state, it's the same color as the text:
image

**Comment by raysan5** [comment]
@furudbat this is a tricky one, I don't one what's the best design for it, also, it could be a good idea to allow multiple toogle-slide-positions, similar to the `GuiToggleGroup()`

**Comment by raysan5** [comment]
@furudbat I try to minimize the `raygui` API, so a `GuiToggleSlider()` (using the group one) should be enough for most users, no need to add 3 new functions to the API. Users requiring more advance functionality can implement it themselfs.

**Comment by furudbat** [comment]
>  this is a tricky one, I don't one what's the best design for it, also, it could be a good idea to allow multiple toogle-slide-positions, similar to the GuiToggleGroup()

Oh, I think I miss understood you, Users can of cause implement their own `GuiToggleGroup` (see last commit).

For the style, I use the SLIDER properties, for the outer box and for the inner toggle, I used the BUTTON style (cuz it fit the best, IMO).
The text alignment of the inner toggle can be set up with `TOGGLE, TEXT_ALIGNMENT`
_I tried to use the SLIDER properties for the inner toggle and it doesn't look good._

_(Sorry for the mixed up use of the style properties, I was not sure how to add new style properties with all the bells and whistles and default values for a new GUI control)_

**Comment by raysan5** [comment]
@furudbat I'm merging it for further review but not sure if I will keep it.

**Pull request merged**
