### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rahulunair**
fix nit with license URI failing

### CODE REVIEW

**Comment by rahulunair** [comment]
ha weird I am still getting 404 wen i click on LICENSE.

> Actually, it can be referenced just as [LICENSE](LICENSE).

Weird, I am still getting a 404 when I click on the LICENSE

**Comment by raysan5** [comment]
@rahulunair yeah, sorry, just updated the previous comment, path to file is relative from repo base path. The comment was referring it from the pull-request.

**Comment by rahulunair** [comment]
closing the PR

**Comment by raysan5** [comment]
@rahulunair ok, just updated it manually.

**Pull request closed without merging**
